services:
  - type: worker
    name: kanger-ai-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: HF_MODEL
        value: "deepseek-ai/DeepSeek-V3"
      - key: ADMIN_ID
        value: "8080874290"
