services:
  - type: web
    name: neirochel-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: "google/gemma-4-31b-it:free"
      - key: ADMIN_ID
        value: "8080874290"
      - key: CHANNEL_USERNAME
        value: "neirochel_official"
